version: '3'
services:
    api-server:
        build:
            context: .
            dockerfile: local.Dockerfile
        container_name: 'api-server'
        volumes:
            - .:/usr/src/app/
        working_dir: /usr/src/app
        command: sh -c "npm install && npm start"
        ports:
            - 4040:4040
